### ISSUE TITLE
Support tilde expansion on filestore path

### ISSUE THREAD

**Issue by susam** [cloudmarker/cloudmarker#17]
We should support [tilde expansion](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01) in any paths read from configuration as much as possible.

For example, currently the `filestore` plugin module accepts a directory path as `path` parameter to write output files.

https://github.com/cloudmarker/cloudmarker/blob/273eadb325f9183f1932272efb3b0ce55e3bda7a/cloudmarker/stores/filestore.py#L11-L18

It should expand tilde (`~`) or (`~user`) in the `path` to the home directory of the user.

Python has a [`os.path.expanduser()`](https://docs.python.org/3.7/library/os.path.html#os.path.expanduser) function that does this. This should be used to do this task. Here is an example usage:

```
>>> import os
>>> os.path.expanduser('~susam')
'/Users/susam'
>>> os.path.expanduser('~susam/foo')
'/Users/susam/foo'
>>> os.path.expanduser('~')
'/Users/susam'
>>> os.path.expanduser('~/foo')
'/Users/susam/foo'
```

**Comment by prateeknischal** [comment]
Added #21 for the issue.
