### ISSUE TITLE
Add more labels for issues

### ISSUE THREAD

**Issue by susam** [cloudmarker/cloudmarker#29]
See the list of issue labels at https://github.com/cloudmarker/cloudmarker/issues/labels.

We have the following issue labels right now which were provided in GitHub by default:

| Label | Description | Color
| --- | --- | --- |
| bug | Something isn't working | #d73a4a |
| duplicate | This issue or pull request already exists | #cfd3d7 |
| enhancement | New feature or request | #63d8cd |
| good first issue | Good for newcomers | #7057ff |
| help wanted | Extra attention is needed | #008672 |
| invalid | This doesn't seem right | #FFA500 |
| question | Further information is requested | #d876e3 |
| wontfix | This will not be worked on | #ffffff |

I am planning to add the following additional labels to better label the issues:

| Label | Description | Color |
| --- | --- | --- |
| refactoring | Code restructuring without affecting external behaviour | ? |
| quality | Test, coverage, or coding style improvements | ? |
| improvement | Functional improvement to an existing feature | ? |
| documentation | Any fixes or improvements in documentation | ? |
| discussion | Discussion on process and other non-coding activities | ? |
| Priority: Low | Issue will be fixed but low priority for now | ? |
| Priority: Medium | Issue will be fixed | ? |
| Priority: High | Issue will be fixed on high priority basis | ? |
| Priority: Critical | Alarming issue that needs to fixed urgently| ? |

Please review these labels and suggest if you would like any additional labels to be added. Please feel free to edit this comment and fill in or alter the color suggestions (if any) in the third column of the new labels.

**Comment by susam** [comment]
Created the labels. I am keeping this issue open for review of the labels and any discussion about it. I will close this issue after a week.

**Comment by r0hi7** [comment]
I have added a few more labels for priorities.

**Comment by susam** [comment]
Thanks @r0hi7. These are good suggestions.

The new labels suggested were:

| Label | Description | Color |
| --- | --- | --- |
| Priority: Low | Issue will be fixed but low priority for now | ? |
| Priority: Medium | Issue will be fixed | ? |
| Priority: High | Issue will be fixed on high priority basis | ? |
| Priority: Critical | Alarming issue that needs to fixed urgently| ? |

The new labels added by me are:

| Label | Description | Color |
| --- | --- | --- |
| priority: low | Minor issue that should be fixed but low on priority for now | ? |
| priority: medium | Feature request or moderate issue that should be addressed | ? |
| priority: high | Major issue that should be fixed soon with high priority | ? |
| priority: critical | Critical issue that should be fixed as soon as possible | ? |

I altered your suggestions a little bit to be consistent with the existing labels and to be a little more descriptive too.

**Comment by susam** [comment]
Closing this issue because it is now more than a week old. The labels discussed above have been added. If you have more suggestions for labels, please reopen this issue and add your suggestions.

**Comment by susam** [comment]
Added a new label:

| Label | Description | Color |
| --- | --- | --- |
| release | Release related activities and changes | ? |
