### ISSUE TITLE
Use tenant and secret as parameters in AzureCloud

### ISSUE THREAD

**Issue by susam** [cloudmarker/cloudmarker#44]
The `AzureCloud` plugin currently accepts the following three parameters: `tenant_id`, `client`, and `key`.

I recommend naming them to:

- `tenant` (remove `_id` from the name to be consistent with `client`)
- `client` (no change required)
- `secret` (to be consistent with keyword argument name for `ServicePrincipalCredentials`)

Also, for future reference, I am noting down the several different terminologies in use for each of these fields. We would have to clarify these differences in documentation in future to avoid any confusion.

| Reference | Field 1 | Field 2 | Field 3 |
| --- | --- | --- | --- |
| [`ServicePrincipalCredentials`][class] parameters | `tenant` | `client_id` | `secret` |
| [`az login`][azcli] option names | `--tenant` | `--username` | `--password` |
| [`az login --help`][azcli] option descriptions | tenant | service principal | client secret |
| [How-to document on creating service principal][howto] | Tenant ID | Application ID | Authentication key |
| [Azure Portal][portal] | Azure Active Directory &raquo; Properties &raquo;  Directory ID | Azure Active Directory &raquo;  App Registrations &raquo;  (an app) &raquo;  Application ID | Azure Active Directory &raquo;  App Registrations &raquo;  (an app) &raquo;  Settings &raquo;  Keys &raquo;  Passwords |

[class]: https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory.serviceprincipalcredentials?view=azure-python
[azcli]: https://docs.microsoft.com/en-us/cli/azure/reference-index#az-login
[howto]: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal
[portal]: http://portal.azure.com/

With different terms in use for the same fields in various official artifacts of Microsoft, I like the recommendation I have provided in this ticket. It also clearly expresses that the `secret` is a secret and therefore must be protected carefully.

**Comment by s-nirali** [comment]
I had noticed the difference in terminologies. Here is one more from the official [Authenticate with the Azure Management Libraries for Python](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-token) that is currently used in the code. :sweat_smile:
